# Generated by Django 5.2.5 on 2025-08-27 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('part', models.CharField(choices=[('A', 'Part A - MCQ'), ('B', 'Part B - True/False'), ('C', 'Part C - Fill in the blanks'), ('D', 'Part D - Short answer (50 words)'), ('E', 'Part E - Long answer (100-120 words)')], max_length=1)),
                ('marks', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('options', models.JSONField(blank=True, null=True)),
                ('correct_answer', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.category')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.level')),
                ('qf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.qf')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.skill')),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.trade')),
            ],
        ),
        migrations.CreateModel(
            name='PaperQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('is_common', models.BooleanField(default=False)),
                ('active_from', models.DateField(blank=True, null=True)),
                ('active_to', models.DateField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.category')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.level')),
                ('qf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.qf')),
                ('questions', models.ManyToManyField(through='questions.PaperQuestion', to='questions.question')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.skill')),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.trade')),
            ],
        ),
        migrations.AddField(
            model_name='paperquestion',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.questionpaper'),
        ),
        migrations.AlterUniqueTogether(
            name='paperquestion',
            unique_together={('paper', 'question')},
        ),
    ]
