# Generated by Django 5.2.5 on 2025-08-27 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_questionupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.questionupload'),
        ),
    ]
