# Generated by Django 5.2.5 on 2025-08-29 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_questionpaper_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='trade',
        ),
        migrations.RemoveField(
            model_name='questionpaper',
            name='trade',
        ),
    ]
