# Generated by Django 5.2.5 on 2025-08-29 15:56

import questions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_remove_question_trade_remove_questionpaper_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='part',
            field=models.CharField(choices=[('A', 'Part A - MCQ'), ('B', 'Part B - True/False'), ('C', 'Part C - Fill in the blanks'), ('E', 'Part E - Long answer (100-120 words)')], max_length=1),
        ),
        migrations.AlterField(
            model_name='questionupload',
            name='file',
            field=models.FileField(upload_to='uploads/', validators=[questions.models.validate_dat_file]),
        ),
    ]
