# Generated by Django 5.2.5 on 2025-08-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_question_part_alter_questionupload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='part',
            field=models.CharField(choices=[('A', 'Part A - MCQ (Single Choice)'), ('B', 'Part B - MCQ (Multiple Choice)'), ('C', 'Part C - MCQ (Other format)'), ('D', 'Part D - Fill in the blanks'), ('E', 'Part E - Long answer (100-120 words)'), ('F', 'Part F - True/False')], max_length=1),
        ),
    ]
