# Generated by Django 5.2.5 on 2025-08-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_questionpaper_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True),
        ),
    ]
