# Generated by Django 5.2.5 on 2025-08-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_alter_questionpaper_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='duration',
            field=models.DurationField(blank=True, help_text='Enter exam duration in format HH:MM:SS (e.g., 01:30:00 for 1h30m)', null=True),
        ),
    ]
