# Generated by Django 5.2.5 on 2025-08-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_alter_questionpaper_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionupload',
            name='decryption_password',
            field=models.CharField(default='default123', max_length=255),
        ),
    ]
