# Generated by Django 5.2.5 on 2025-08-31 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_questionupload_decryption_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='category',
            new_name='trade',
        ),
        migrations.RenameField(
            model_name='questionpaper',
            old_name='category',
            new_name='trade',
        ),
    ]
