# Generated by Django 5.2.5 on 2025-08-31 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_rename_category_question_trade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='level',
        ),
        migrations.RemoveField(
            model_name='question',
            name='qf',
        ),
        migrations.RemoveField(
            model_name='question',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='questionpaper',
            name='level',
        ),
        migrations.RemoveField(
            model_name='questionpaper',
            name='qf',
        ),
        migrations.RemoveField(
            model_name='questionpaper',
            name='skill',
        ),
    ]
