# Generated by Django 5.2.5 on 2025-08-29 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_remove_question_trade_remove_questionpaper_trade'),
        ('reference', '0001_initial'),
        ('registration', '0003_remove_candidateprofile_trade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trade',
        ),
    ]
