# Generated by Django 5.2.5 on 2025-08-29 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_delete_trade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Trade', 'verbose_name_plural': 'Trades'},
        ),
    ]
