# Generated by Django 5.2.5 on 2025-08-31 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_rename_categories_examdayavailability_trades'),
        ('questions', '0012_rename_category_question_trade_and_more'),
        ('reference', '0003_alter_category_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Trade',
        ),
    ]
