# Generated by Django 5.2.5 on 2025-08-31 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_remove_question_level_remove_question_qf_and_more'),
        ('reference', '0004_rename_category_trade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.DeleteModel(
            name='QF',
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
