# Generated by Django 5.2.5 on 2025-08-27 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0001_initial'),
        ('questions', '0001_initial'),
        ('reference', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(default='SCHEDULED', max_length=20)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_assignments', to=settings.AUTH_USER_MODEL)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='centers.center')),
                ('common_paper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='common_assignments', to='questions.questionpaper')),
                ('primary_paper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_assignments', to='questions.questionpaper')),
            ],
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('objective_score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('practical_marks', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('viva_marks', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attempt', to='exams.examassignment')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('capacity', models.PositiveSmallIntegerField(default=40)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centers.center')),
            ],
            options={
                'unique_together': {('center', 'date', 'start_time')},
            },
        ),
        migrations.AddField(
            model_name='examassignment',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exams.shift'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given', models.JSONField(blank=True, null=True)),
                ('text_answer', models.TextField(blank=True)),
                ('auto_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('evaluator_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('final_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.question')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.examattempt')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
        migrations.CreateModel(
            name='ExamDayAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('categories', models.ManyToManyField(related_name='available_on', to='reference.category')),
            ],
            options={
                'unique_together': {('date',)},
            },
        ),
        migrations.AlterUniqueTogether(
            name='examassignment',
            unique_together={('candidate', 'shift')},
        ),
    ]
