# Generated by Django 5.2.5 on 2025-08-27 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_questionupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionUpload',
        ),
    ]
