# Generated by Django 5.2.5 on 2025-08-31 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_delete_questionupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examdayavailability',
            old_name='categories',
            new_name='trades',
        ),
    ]
