# Generated by Django 5.2.5 on 2025-08-27 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0001_initial'),
        ('reference', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('army_no', models.CharField(max_length=50, unique=True)),
                ('rank', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('father_name', models.CharField(max_length=150)),
                ('enrolment_no', models.CharField(blank=True, max_length=100)),
                ('doe', models.DateField(verbose_name='Date of Enrolment')),
                ('aadhar_number', models.CharField(blank=True, max_length=12)),
                ('unit', models.CharField(max_length=120)),
                ('fmn_bde', models.CharField(blank=True, max_length=120, verbose_name='Fmn (Bde)')),
                ('fmn_div', models.CharField(blank=True, max_length=120, verbose_name='Fmn (Div)')),
                ('fmn_corps', models.CharField(blank=True, max_length=120, verbose_name='Fmn (Corps)')),
                ('fmn_comd', models.CharField(blank=True, max_length=120, verbose_name='Fmn (Comd)')),
                ('trg_centre', models.CharField(blank=True, max_length=150, verbose_name='Training Centre')),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('photograph', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.category')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='centers.center')),
                ('level_of_qualification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates_level', to='reference.level')),
                ('nsqf_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates_nsqf', to='reference.level')),
                ('qf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.qf')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.qualification')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.skill')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.trade')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
