# Generated by Django 5.2.5 on 2025-08-29 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_candidateprofile_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='trade',
        ),
    ]
