# Generated by Django 5.2.5 on 2025-08-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_remove_candidateprofile_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='practical_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='viva_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
    ]
