# Generated by Django 5.2.5 on 2025-08-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_candidateprofile_practical_marks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='center',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='fmn_bde',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='fmn_comd',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='fmn_corps',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='fmn_div',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='level_of_qualification',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='qf',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='trg_centre',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='unit',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='credits',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='duration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='exam_center',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='trade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='training_center',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='nsqf_level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='qualification',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
