# Generated by Django 5.2.5 on 2025-08-31 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_remove_candidateprofile_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='enrolment_no',
        ),
    ]
