# Generated by Django 5.2.5 on 2025-08-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField(blank=True)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('capacity', models.PositiveSmallIntegerField(default=40)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
