# Generated by Django 5.2.5 on 2025-08-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='code',
        ),
        migrations.RemoveField(
            model_name='center',
            name='name',
        ),
        migrations.AddField(
            model_name='center',
            name='comd',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='center',
            name='conducting_Fmn',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='center',
            name='exam_Center',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
